[phases.setup]
nixPkgs = ["nodejs_20", "python310", "python310Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r src/python/requirements.txt"
]

[start]
cmd = "npm start"
