# Nixpacks configuration for Railway deployment
# This ensures Node.js, Python and ffmpeg are available

[phases.setup]
nixPkgs = ["nodejs_18", "python39", "python39Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "npm start"
